### ISSUE TITLE
'News' page on Django New layout

### ISSUE THREAD

**Issue by enghamzasalem** [Zakyat/zakyat-backend#16]
Acceptance Criteria:
Note(we are not using Django admin layout)
- Charity employees will log in through Django to access the News page and provide (Create, Edit, Delete) functionality the same as Django Admin pages.
Tasks:
- 
- 
- 
-

**Comment by kevlinsky** [comment]
Questions for clear view on criteria:

- Should registration and authorization be implemented? If it is, should employees register and login by form for standart users or they will have an separate dashboard for example.
- If the registration and authorization will be implemented later, can I just refer on existing table and use LoginRequiredMixin?
- Are there any read-only fields of news which cannot be edited?

Tasks:

- [ ] Create a ListView of all News ordered by publishing time. In top of the page put a creation form of the fresh News by using standart News Schema with widgets.
- [ ] Create an UpdateView without read-only fields to edit a news. Employee will be redirected to this page by clicking on Edit button.
- [ ] Create a DetailView of the News which will be used when employee click on the title of the News. Realize urls by using slugs. On this page exists the same functionality of editing and deleting like on list of news page.
- [ ] Realize deleting a news on the 'list news' page by using Ajax requests. Delete functionality on DetailView will be realized with common DELETE method with redirecting on 'list news' page.

**Comment by enghamzasalem** [comment]
Q1:
Yes, you should; Employees have a different login page than users; However for now you can use the same login Django admin or create your own (workaround) until the designer gives us login page design.

Q2: 
Yes, you can. and you can implement your own simple login/register page 

Q3:
created_by is read-only.
