### ISSUE TITLE
'Partners' page

### ISSUE THREAD

**Issue by enghamzasalem** [Zakyat/zakyat-backend#17]
Acceptance Criteria:
Note(we are not using Django admin layout)

If an employee has a right to work with 'Partners' data
-  List of all partners
-  Provide (Create, Edit, Delete) functionality the same as Django Admin pages.

Tasks:
-
-

**Comment by KhaliullinBulat** [comment]
To solve this issue i'm going to:
1. Create partners page (partners.html)
2. Create view (ListView CBV)
3. Create forms for creating, editing and deleting operations
4. Create urls for creating, editing and deleting operations
5. Create views for rendering urls in previous way
