### ISSUE TITLE
'Staff' page (employee page)

### ISSUE THREAD

**Issue by enghamzasalem** [Zakyat/zakyat-backend#18]
Acceptance Criteria:
Note(we are not using Django admin layout)

If an employee has a right to work with 'Staff' data
- Show list of all employees
- Create create&edit&delete functions

Employees can't register themself in our system. The first charity employee would be created by super admin only, who can add him rights for creating other admins.

Functionality the same as Django Admin pages.

Tasks:
- 
-

**Comment by Raynur2000** [comment]
I am planning to realize the following steps to solve the issue:

1. Create 2 templates. First for a list of staff and the second one is to create/edit/delete. 
2. Create StaffListView (CBV) in views.py to show all staff.
3. Create 2 Django forms for creating and editing in forms.py.
4. Create 2 FormView (CBV) handlers.
5. Write paths for URLs: 'admin/staffs/', 'admin/staff/create', 'admin/staff/edit/<int:id>/' and 'admin/staff/delete/<int:id>'.
