### ISSUE TITLE
'Login' page for employee

### ISSUE THREAD

**Issue by enghamzasalem** [Zakyat/zakyat-backend#19]
Acceptance Criteria:
Note(we are not using Django admin layout)
- Create a 'login' page for charity employees. 
- 'Login' page must have a 'Forget password' button (Issue #21)

Tasks:
- 
-

**Comment by lyf2000** [comment]
The plan of issue solving (all changes will be in __accounts__ app):

- create **login** html page and view
- use simle integrated django logining system
