### ISSUE TITLE
Fix 'Gatherings' models

### ISSUE THREAD

**Issue by Yasinaaa** [Zakyat/zakyat-backend#30]
**Fix that logic in Django models if it's not correct**

If a user input all information to the user_info table [check #14] for asking help, next step he/she needs to **send request**, where user input description (заявление на оказание помощи) and his category_of_needy. After he/she sends request, it become in request_status = 'in_processing'.  

```sql
Table requests{ 
  id int [pk, increment]
  user_info_id int [ref: - user_info.id]
  description varchar [not null]
  documents base64[]
  request_status requests_status
  gathering_id int [ref: - gatherings.id]
  updated_at datetime
  created_at datetime [default: `now()`]
  category_of_needy categories_of_needy [note: 'Nullable']
  denying_reason varchar [note: 'Nullable']
}

Enum requests_status{
  in_processing
  denied
  negotiation
  gathering_opened
  gathering_closed
}
```
>desc. [ref: - user_info.id] means 'one-to-one' relationship

If an employee saw the request but didn't answer, request_status changes to = 'negotiation'.
If an employee decides to deny the request, request_status changes to = 'denied' and denying_reason field mustn't be null.
If an employee decides to accept the request, request_status changes to = 'gathering_opened' and gathering_id field mustn't be null.
If an employee closes the request that had a gathering, request_status changes to = 'gathering_closed'.

>desc.  gathering = сбор денег

```sql
Table gatherings{ 
  id int [pk, increment]
  request_id int [ref: - requests.id]
  project_id int [ref: < project.id]
  employee_id int [ref: < employees.id]
  title varchar
  description varchar
  goal_sum int
  current_sum int
  status bool 
  created_at datetime [default: `now()`] 
  updated_at datetime
  closed_at datetime
  payment_options payment_options[]
}
```
>desc. status bool means opened or closed that gathering. 

```sql
Table payment_options{
   id int [pk, increment]
   title varchar
   description varchar
}
```

there are id=0 -> acquiring(web-site) payment system, id=1 -> cash money and other payments that could be added by employees.

Also not only users can open gatherings, but also employees can open gathering for the project, and there wouldn't be request.

**Comment by Yasinaaa** [comment]
```sql
Table payment_options{
   id int [pk, increment]
   title varchar
   description varchar
}```
there are id=0 -> acquiring(web-site) payment system, id=1 -> cash money, and other payments that could be added by employees.

**Comment by lyf2000** [comment]
How I will solve this issue:

1. Create abstract models with specified fields above: `PaymentOption`
1. Change `Request` model (add new fields)
1. Change `Statuses`
1. Create approriate methods in model `Request` for the sake of implementing the part of business logic
1. Change `Campaign` model (add fields)
