### ISSUE TITLE
'Employees' admin page make with templates

### ISSUE THREAD

**Issue by Yasinaaa** [Zakyat/zakyat-backend#35]
This 'Employees' page must include such things:
1) List of employees (Last added user must be at the beginning of the list)
2) When click to the employee-item, it must open info with all information about them. 
2.1) There are need to be 'delete' an employee function
2.2) There are need to be 'edit' an employee function
3) Create an employee view
4) Show count of all employees. This count can change if admin use search filters
5) Search filters: by text in all fields, by date 

View of template for this page you can see [here](https://django-dashboard-shards.appseed.us/ui-tables.html)
Forms view [here](https://django-dashboard-shards.appseed.us/ui-components.html)
Code of this template [here](https://github.com/app-generator/django-dashboard-shards)

**Comment by Raynur2000** [comment]
My plan:
1. Pull up a template for a list of employees.
2. Pull up a template for the employee create/edit page.
3. Pull up a template for the employee delete page.
4. Create an employee view.
5. Make search filters: by text in all fields, by date.
