### ISSUE TITLE
'Gatherings' admin page make with templates

### ISSUE THREAD

**Issue by Yasinaaa** [Zakyat/zakyat-backend#36]
This 'Gatherings' page must include such things:
1) List of gatherings: all, only open, only close
2) When click to the gathering-item, it must open full info about it. 
2.1) There are needs to be 'force close' a gathering function, with reason field.
2.2) There is a need to be button that opens all payments history of that gathering 
3) Create a gathering view
3.1) Create payment_options view
4) Show count of all gatherings. This count can change if admin use search filters
5) Search filters: by text in all fields, by date

**Comment by lyf2000** [comment]
Plan of work:

- Create pages using CBV\view\django-filters

**Comment by lyf2000** [comment]
Closed in #74
