### ISSUE TITLE
'Banners' admin page make with templates

### ISSUE THREAD

**Issue by Yasinaaa** [Zakyat/zakyat-backend#38]
- [x] Create a page of all lists of existed banners
- [x] Create a page for creation banner function
- [x] Create delete banner function

A banner is just an image and title

**Comment by AnteeOne** [comment]
To solve this issue i'm planning to realize next steps:

- [ ] Create banner Model

- [ ] Create banners list page (banners_list.html)

- [ ] Create banner detail page (banner_detail.html)

- [ ] Create page for banner editing (banner_edit.html)

- [ ] Create forms for banner creating , updating and deleting

- [ ] Create view file

- [ ] Create urls file
