### ISSUE TITLE
Fix 'Partners' view page

### ISSUE THREAD

**Issue by Yasinaaa** [Zakyat/zakyat-backend#76]
Now
<img width="1389" alt="Screenshot 2020-07-20 at 08 52 10" src="https://user-images.githubusercontent.com/10158025/87904345-bfb4e600-ca66-11ea-9f5a-35b06e81f2ad.png">

Fix to
<img width="1374" alt="Screenshot 2020-07-20 at 08 52 10 2" src="https://user-images.githubusercontent.com/10158025/87904354-c7748a80-ca66-11ea-8e2d-080fbf26742c.png">

**Comment by AnteeOne** [comment]
Also fix this
![image](https://user-images.githubusercontent.com/57267956/88067043-29bcb080-cb77-11ea-859e-e1f73d9aee13.png)
to
![image](https://user-images.githubusercontent.com/57267956/88067166-51137d80-cb77-11ea-8e66-f4e7dbbb793b.png)
