### ISSUE TITLE
Connect VK SDK for user registration and login

### ISSUE THREAD

**Issue by Yasinaaa** [Zakyat/zakyat-backend#87]
Need to connect VK API for user registration.

**Comment by AnteeOne** [comment]
To solve this issue i'm going to realize next steps:

- [ ] Create new app in Zakyat folder - for user's authorization

- [ ] (Maybe  I'm going to use django-allauth for solving this issue)

- [ ] Create test template for authorization

- [ ] Connect vk sdk for authorization (As i know , this may be simplified with django-allauth)

**Comment by AnteeOne** [comment]
- [ ] Fix user deleting
- [ ] Create view , that will create decorators for standart django users

**Comment by AnteeOne** [comment]
Now i have some problems with connecting instagram ouath(get secret keys and id for testing) , cause i cannot create new webapplication at facebook while facebook admins checking my acc
![image](https://user-images.githubusercontent.com/57267956/88536622-d504b400-d014-11ea-8b81-db17371d7844.png)
![image](https://user-images.githubusercontent.com/57267956/88536674-e9e14780-d014-11ea-854d-b59e6609c5ba.png)
